---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: username/core:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sup
  labels:
    app: sup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sup
  template:
    metadata:
      labels:
        app: sup
    spec:
      containers:
        - name: sup
          image: username/sup:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard service
  labels:
    app: dashboard service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard service
  template:
    metadata:
      labels:
        app: dashboard service
    spec:
      containers:
        - name: dashboard service
          image: username/dashboard service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    app: core
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: core


---


apiVersion: v1
kind: Service
metadata:
  name: sup
  labels:
    app: sup
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sup


---


apiVersion: v1
kind: Service
metadata:
  name: dashboard service
  labels:
    app: dashboard service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dashboard service

