apiVersion: apps/v1
kind: Deployment
metadata:
  name: sup
  labels:
    app: sup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sup
  template:
    metadata:
      labels:
        app: sup
    spec:
      containers:
        - name: sup
          image: "username/sup:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
